<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/08/2018
 * Time: 4:21 PM
 */
?>

CREATE TABLE `NewTable` (
`smsID`  int(11) NULL AUTO_INCREMENT ,
`tran_due`  datetime NULL ,
`s_date`  date NULL ,
`sms_to`  varchar(20) NULL ,
`sms_msg`  varchar(200) NULL ,
`paid`  double(11,2)  NULL DEFAULT 0  ,
`spend`  double(11,2) NULL DEFAULT 0 ,
`statusID`  int(3) NULL DEFAULT 1 ,
PRIMARY KEY (`smsID`)
)
;

SELECT
message.smsID,
message.userID,
Sum(message.paid) AS total_paid,
Sum(message.spend) AS total_spend,
message.s_date
FROM
message
GROUP BY
message.smsID,
message.userID

