<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 02/08/2018
 * Time: 5:45 AM
 */

function admin_menu_sidebar(){

    $url = $_SESSION['page-url'];
    $url_token = $_SESSION['token'];
    return"
        <ul class='list-unstyled navbar__list'>
            <li class='active has-sub'>
                <a href='{$url}?page=dashboard&token={$url_token}'>
                    <i class='fas fa-tachometer-alt'></i>Dashboard</a>
            </li>        
            </li>
                <li class='has-sub'>
                    <a class='js-arrow' href='#'>
                    <i class='fas fa-copy'></i>User Account</a>
                    <ul class='navbar-mobile-sub__list list-unstyled js-sub-list'>
                        <li>
                        <a href='{$url}?page=all-user-account&token={$url_token}'>User</a>
                        </li>
                        <li>
                        <a href='{$url}?page=register&token={$url_token}'>Register</a>
                        </li>
                        <li>
                        <a href='{$url}?page=top-up&token={$url_token}'>Top Up Credit</a>
                        </li>
                    </ul>
                </li>
            <li>
                <a href='{$url}?page=send-message&token={$url_token}'>
                    <i class='fas fa-calendar-alt'></i>New Message</a>
            </li>
            <li>
                <a href='{$url}?page=address-book&token={$url_token}'>
                    <i class='fas fa-book'></i>Address Book</a>
            </li>
            <li>
                <a href='{$url}?page=drafts&token={$url_token}'>
                    <i class='fas fa-file-text'></i>Drafts</a>
            </li>
            <li>
                <a href='{$url}?page=sent-item&token={$url_token}'>
                    <i class='fas fa-envelope'></i>Sent Item</a>
            </li>
            <li>
                <a href='{$url}?page=delete-item&token={$url_token}'>
                    <i class='fas fa-trash'></i>Delete Item</a>
            </li>
            
            <li class='has-sub'>
                    <a class='js-arrow' href='#'>
                    <i class='fas fa-copy'></i>Builder</a>
                    <ul class='navbar-mobile-sub__list list-unstyled js-sub-list'>
                        <li>
                        <a href='{$url}?page=create-sql&token={$url_token}'>Create SQL</a>
                        </li>
                        <li>
                        <a href='register.html'>Register</a>
                        </li>
                        <li>
                        <a href='forget-pass.html'>Forget Password</a>
                        </li>
                    </ul>
            </li>
            <li>
                <a href='{$url}?page=chat-message&token={$url_token}'>
                    <i class='fas fa-file-text'></i>chat</a>
            </li>
        </ul>
    ";
}


function main_menu_sidebar(){

    $url = $_SESSION['page-url'];
    $url_token = $_SESSION['token'];
    return"
        <ul class='list-unstyled navbar__list'>
            <li class='active has-sub'>
                <a href='{$url}?page=dashboard&token={$url_token}'>
                    <i class='fas fa-tachometer-alt'></i>Dashboard</a>
            </li>
            <li>
                <a href='{$url}?page=send-message&token={$url_token}'>
                    <i class='fas fa-calendar-alt'></i>New Message</a>
            </li>
            <li>
                <a href='{$url}?page=address-book&token={$url_token}'>
                    <i class='fas fa-book'></i>Address Book</a>
            </li>
            <li>
                <a href='{$url}?page=drafts&token={$url_token}'>
                    <i class='fas fa-file-text'></i>Drafts</a>
            </li>
            <li>
                <a href='{$url}?page=sent-item&token={$url_token}'>
                    <i class='fas fa-envelope'></i>Sent Item</a>
            </li>
            <li>
                <a href='{$url}?page=delete-item&token={$url_token}'>
                    <i class='fas fa-trash'></i>Delete Item</a>
            </li>
            <li>
                <a href='{$url}?page=chat-message&token={$url_token}'>
                    <i class='fas fa-file-text'></i>chat</a>
            </li>
        </ul>
    ";
}


function header_mobile_side_main_menu(){
    $url = $_SESSION['page-url'];
    $url_token = $_SESSION['token'];

    return"
        <ul class='navbar-mobile__list list-unstyled'>
            <li class='active has-sub'>
                <a href='{$url}?page=dashboard&token={$url_token}'>
                    <i class='fas fa-tachometer-alt'></i>Dashboard</a>
            </li>
            <li>
                <a href='{$url}?page=send-message&token={$url_token}'>
                    <i class='fas fa-calendar-alt'></i>New Message</a>
            </li>
            <li>
                <a href='{$url}?page=address-book&token={$url_token}'>
                    <i class='fas fa-book'></i>Address Book</a>
            </li>
            <li>
                <a href='{$url}?page=drafts&token={$url_token}'>
                    <i class='fas fa-file-text'></i>Drafts</a>
            </li>
            <li>
                <a href='{$url}?page=sent-item&token={$url_token}'>
                    <i class='fas fa-envelope'></i>Sent Item</a>
            </li>
            <li>
                <a href='{$url}?page=delete-item&token={$url_token}'>
                    <i class='fas fa-trash'></i>Delete Item</a>
            </li>
            <li>
                <a href='{$url}?page=chat-message&token={$url_token}'>
                    <i class='fas fa-file-text'></i>chat</a>
            </li>
        </ul>
    ";
}

