<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/08/2018
 * Time: 10:02 AM
 */

if (!isset($_POST['email'])){
    $headers("location: index.php?u=recovery");
    exit();
}else{
    $email = $_POST['email'];

    $sql = "select * from user_account where email ='".$email."'";
    $result = $conn->query($sql);
    $r = $result->fetch_assoc();

    $to = $r['email'];
    $subject = "SMS BOX: User login details";
    $txt = " Username:". $r['username']."<br> Password:". $r['passwd'];
    $headers = "From: webmaster@example.com";

    $send = mail($to,$subject,$txt,$headers);

    if ($send == TRUE){
        echo "send";
    }else{
        echo "error";
    }
}


