<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/08/2018
 * Time: 10:02 AM
 */

require_once  "Mail.php";

if (!isset($_POST['email'])){
    $headers("location: index.php?u=recovery");
    exit();
}else{
    $email = $_POST['email'];

    $sql = "select * from user_account where email ='".$email."'";
    $result = $conn->query($sql);
    $r = $result->fetch_assoc();

    $to = $r['email'];
    $subject = "SMS BOX: User login details";
    $username = $r['username'];
    $password = $r['passwd'];
    $txt = " Username:". $r['username']."\r\n Password:". $r['passwd'];

    $headers['From'] = "info@iquipedigita.com";
    $header['To'] = $to;
    $headers['Subject']="Recover Login Details";

    $body = " Username:".$username."\r\n Password:".$password;

    $smtpinfo["host"] = "smtp.iquipedigital.com";
    $smtpinfo["port"] = "25";
    $smtpinfo["auth"] = true;
    $smtpinfo["username"] = "info@iquipedigital.com";
    $smtpinfo["password"] = "passwd8282";

    // Create the mail object using the Mail::factory method
    $mail_object =& Mail::factory("smtp", $smtpinfo);

    $mail_object->send($to, $headers, $body);

}


