<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/08/2018
 * Time: 9:12 AM
 */

session_start();

$_SESSION['page-url'] = "navigation.php";

if ($_SERVER["REQUEST_METHOD"] == "POST"){

    $date = date("Y-m-d");
    $username = $_POST['username'];
    $email = $_POST['email'];
    $password = $_POST['password'];
    //$mobile = $_POST['mobile'];

    $api = md5(md5($username."x".$password."x".$email,true));

    $add = "INSERT INTO `user_account` (`date_created`,`username`, `passwd`, `email`, `api_key`) VALUES ('$date','$username', '$password', '$email', '$api')";
    $result = $conn->query($add);

    if ($result == TRUE){
        $_SESSION['token'] = $api;
        $_SESSION['user-name'] = $username;
        $_SESSION['email'] = $email;
        header("location: navigation.php?page=dashboard&token=$api");
    }else{
      header("location: index.php?u=sign-up");
    }
}