<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/08/2018
 * Time: 9:12 AM
 */

session_start();

$_SESSION['page-url'] = "navigation.php";

if ($_SERVER["REQUEST_METHOD"] == "POST"){

    $time = date("Y-m-d H:i:s");
    $date = date("Y-m-d");
    $username = $_POST['username'];
    $email = $_POST['email'];
    //$password = $_POST['password'];
    $mobile = $_POST['mobile'];

    $user_check = "SELECT * FROM `get_user_account` where email='".$email."'";
    $user_check_result = $conn->query($user_check);
    $check = $user_check_result->fetch_assoc();

    if ($check['email'] === $email || $check['mobile1'] == $mobile){

        echo"the email address has already been used";
        exit();

    }else{

        $api = md5(md5($username."x".$password."x".$email,true));

        $add = "INSERT INTO `user_account` (`date_created`,`username`, `email`, `mobile`, `api_key`) VALUES ('$date','$username', '$email', '$mobile', '$api')";
        $result = $conn->query($add);
        $last = $conn->insert_id;

        if (isset($last)){

        $free_sms="INSERT INTO `account` (`userID`, `tranDate`, `details`, `ref`, `paid`) VALUES ('$api', '$time', 'FREE SMS', 'FREE', '5')";
        $result = $conn->query($free_sms);
        $last_free_sms_account = $conn->insert_id;

            $_SESSION['sms-user-id'] = $last;
            $_SESSION['token'] = $api;
            $_SESSION['user-name'] = $username;
            $_SESSION['email'] = $email;

            //generate password
            $length = 5;
            $gen_password = "";
            $possible = "0123456789abcdefghijklmnopqrstuvwxyz";
            $i = 0;
            while ($i < $length) {
                $char = substr($possible, mt_rand(0, strlen($possible)-1), 1);
                if (!strstr($gen_password, $char)) {
                    $gen_password .= $char;
                    $i++;
                }
            }


            $respone = new stdClass();
            $bulksms = new stdClass();
            $request = new stdClass();
            //username from SMSAPI

            $bulksms->username = 'bsgh-iquipe';
            //or 'password' => md5('open-text-password'),
            $bulksms->password = 'passwd82';
            //destination number
            $request->to = $mobile;
            //sender name has to be active
            $request->from = "smsbox";
            //message content
            $request->message = "Welcome to SMSbox247 share sms with your love ones.\n Username: ".$username ."\n Password: ". $gen_password ."\n Please change password when login \n Thanks";
            //API http

            $url = 'http://sms.bernsergsolutions.com:8080/bulksms/bulksms?';

            $c = curl_init();
            curl_setopt($c,CURLOPT_URL,$url);
            curl_setopt($c,CURLOPT_POST,true);
            curl_setopt($c,CURLOPT_POSTFIELDS, 'username='.$bulksms->username.'&password='.$bulksms->password.
                '&type=0&dlr=1&destination='.$request->to.'&source='.$request->from.'&message='.$request->message);
            curl_setopt($c,CURLOPT_RETURNTRANSFER,true);
            $content = curl_exec($c);
            curl_close($c);

            $str_total = strlen($content);
            $text = 4 - $str_total;

            $msg = substr($content,0,$text);

            if ($msg == 1701){
            header("location: navigation.php?page=account&token=$api");
            }else{

                $del ="DELETE FROM `user_account` WHERE (`userID`='$last')";
                $result = $conn->query($del);

                $del ="DELETE FROM `account` WHERE (`creditID`='$last_free_sms_account')";
                $result = $conn->query($del);

                echo"Login details cant be generated, Try again later";
            }

        }else{
            header("location: index.php?u=sign-up");
        }
    }
}