<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/08/2018
 * Time: 9:12 AM
 */

session_start();

$_SESSION['page-url'] = "navigation.php";

if ($_SERVER["REQUEST_METHOD"] == "POST"){

    $time = date("Y-m-d H:i:s");
    $date = date("Y-m-d");
    $username = $_POST['username'];
   // $email = $_POST['email'];
    $password = $_POST['password'];
    $mobile = $_POST['mobile'];

    $user_check = "SELECT * FROM `get_user_account` where email='".$email."'";
    $user_check_result = $conn->query($user_check);
    $check = $user_check_result->fetch_assoc();

    if ($check['email'] === "$email"){

        echo"the email address has already been used";
        exit();

    }else{

        $api = md5(md5($username."x".$password."x".$email,true));

        $add = "INSERT INTO `user_account` (`date_created`,`username`, `passwd`, `mobile1`, `api_key`) VALUES ('$date','$username', '$password', '$mobile', '$api')";
        $result = $conn->query($add);
        $last = $conn->insert_id;

        if (isset($last)){

        $free_sms="INSERT INTO `account` (`userID`, `tranDate`, `details`, `ref`, `paid`) VALUES ('$api', '$time', 'FREE SMS', 'FREE', '5')";
        $result = $conn->query($free_sms);

            $_SESSION['sms-user-id'] = $last;
            $_SESSION['token'] = $api;
            $_SESSION['user-name'] = $username;
            $_SESSION['email'] = $email;
            header("location: navigation.php?page=account&token=$api");
        }else{
            header("location: index.php?u=sign-up");
        }
    }
}