<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 04/08/2018
 * Time: 9:04 AM
 */


?>
<hr>
<div class="col-lg-12">
    <div class="card">
        <div class="card-header">
            <strong>Message</strong>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <input type="hidden" name="page" value="model">
            <div class="card-body card-block">
                <div class="form-horizontal">
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="text-input" class=" form-control-label">Time</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="text" id="text-input" name="time" value="<?php echo date("Y-m-d H:i:s")?>" placeholder="Text" class="form-control">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="email-input" class=" form-control-label">Mobile Number</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="text" id="text-input" name="mobile" value="<?php echo $mobile;?>" placeholder="233548200000" class="form-control">
                            <small class="help-block form-text">Please enter mobile number</small>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="textarea-input" class=" form-control-label">Message</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <textarea name="message"  id="textarea-input"  rows="9" placeholder="Content..." class="form-control"><?php echo $msg?></textarea>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col col-md-3">
                            <label for="select" class=" form-control-label">Sender ID</label>
                        </div>
                        <div class="col-12 col-md-9">
                            <input type="text" id="text-input" name="sender-id" value="<?php echo $senderID;?>" placeholder="smsbox" class="form-control">
                            <small class="help-block form-text">your nice name, company name or mobile number e,g. smsbox </small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" name="submit" value="<?php echo $button->value;?>" class="<?php echo $button->css;?>">
                    <i class="<?php echo $button->icon;?>"></i><?php echo $button->label;?>
                </button>
                <button type="reset" class="btn btn-danger btn-sm">
                    <i class="fa fa-ban"></i> Reset
                </button>
            </div>
        </form>
    </div>
</div>
