<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/08/2018
 * Time: 7:58 PM
 */

if (isset($_SESSION['user-name'])){
    $name =  $_SESSION['user-name'];
}else{
    $name ="";
}

if (isset($_SESSION['token'])){
    $token = $_SESSION['token'];
}else{
    $token ="";
}

?>

<div class="col-lg-6">
    <div class="card">
        <div class="card-header">Credit Card</div>
        <div class="card-body">
            <div class="card-title">
                <h3 class="text-center title-2">Pay Invoice</h3>
            </div>
            <hr>
            <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"])?>" method="GET" novalidate="novalidate">
                <input type="hidden" name="page" value="model">
                <input type="hidden" name="token" value="<?php echo $_GET['token']?>">
                <div class="form-group">
                    <label for="cc-payment" class="control-label mb-1">Payment amount</label>
                    <input id="cc-pament" name="cc-payment" type="text" readonly class="form-control" aria-required="true" aria-invalid="false" value="1.00">
                </div>
                <div class="form-group has-success">
                    <label for="cc-name" class="control-label mb-1">Name on card</label>
                    <input id="cc-name" name="cc-name" type="text" readonly value="iQuipe Digital" class="form-control cc-name valid" data-val="true" data-val-required="Please enter the name on card"
                           autocomplete="cc-name" aria-required="true" aria-invalid="false" aria-describedby="cc-name-error">
                    <span class="help-block field-validation-valid" data-valmsg-for="cc-name" data-valmsg-replace="true"></span>
                </div>
                <div class="form-group">
                    <label for="cc-number" class="control-label mb-1">Mobile Pay Number</label>
                    <input id="cc-number" name="cc-number" type="tel" class="form-control cc-number identified visa" value="800332548263738" data-val="true"
                           data-val-required="Please enter the card number" data-val-cc-number="Please enter a valid card number"
                           autocomplete="cc-number">
                    <span class="help-block" data-valmsg-for="cc-number" data-valmsg-replace="true"></span>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="cc-exp" class="control-label mb-1">Expiration</label>
                            <input id="cc-exp" name="cc-exp" type="tel" class="form-control cc-exp" value="12/18" data-val="true" data-val-required="Please enter the card expiration"
                                   data-val-cc-exp="Please enter a valid month and year" placeholder="MM / YY"
                                   autocomplete="cc-exp">
                            <span class="help-block" data-valmsg-for="cc-exp" data-valmsg-replace="true"></span>
                        </div>
                    </div>
                    <div class="col-6">
                        <label for="x_card_code" class="control-label mb-1">Security code reference</label>
                        <div class="input-group">
                            <input id="x_card_code" name="x_card_code" type="text" class="form-control cc-cvc" value="<?php echo date("Ymdhis")?>" data-val="true" data-val-required="Please enter the security code"
                                   data-val-cc-cvc="Please enter a valid security code" autocomplete="off">

                        </div>
                    </div>
                </div>
                <div>
                    <button id="payment-button" type="submit" name="submit" value="payment" class="btn btn-lg btn-info btn-block">
                        <i class="fa fa-lock fa-lg"></i>&nbsp;
                        <span id="payment-button-amount">Make Payment</span>
                        <span id="payment-button-sending" style="display:none;">Sending…</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="col-lg-6">
    <!-- TOP CAMPAIGN-->
    <div class="top-campaign">
        <h3 class="title-3 m-b-30">Cash Available <?php echo user_balance($conn);?></h3>
        <div class="table-responsive">
            <table class="table table-top-campaign">
                <tbody>
                <?php user_account($conn);?>
                </tbody>
            </table>
        </div>
    </div>
    <!--  END TOP CAMPAIGN-->
</div>