<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/08/2018
 * Time: 7:44 AM
 */

if (!isset($_REQUEST['submit'])){
    echo "action not define";
}else{
     $action = $_REQUEST['submit'];
     $token = $_REQUEST['token'];

     if (!$_SESSION['token'] === $token){
         echo "<h1>SERVER SESSION ERROR</h1><P>wrong token or cant find token. click here to go <a href='{$_SERVER['HTTP_REFERER']}'>back</a> </P>";
     }else{

         switch ($action){

             case "payment";
                //echo "payment";
                //payment($conn);
                include "mazzuma.payment.module";
             break;

             case"add-contact";
                //echo"add.contact";
                 add_contact($conn);
             break;

             case"update-contact";
                //echo"update contact";
                 edit_contact($conn);
             break;

             case"send-message";
                //echo"send-message";
                 //send_message($conn);
                 $userID = $_SESSION['token'];
                 $sql = "SELECT * FROM get_balance where userID='$userID'";
                 $result = $conn->query($sql);
                 $record = $result->fetch_assoc();

                 if($record['bal'] > 1.00){
                     include "sms.send.module";
                 }else{
                    echo "<h1>LOW FUNDS. TOP UP WALLET</h1><br>please click here to <a href='navigation.php?page=user.bill&token={$_SESSION['token']}'>Top-up</a> or to <a href='{$_SERVER['HTTP_REFERER']}'>return back.</a>";
                 }
             break;

             case"save-message";
                echo"save message";
                 add_draft_message($conn);
             break;

             case"del.contact";
                //echo"del contact";
                delete_contact($conn);
             break;

             case "status";
                if ($_GET['u'] == 2){
                    send_to_bin($conn);
                }elseif ($_GET['u'] == 1){
                    restore_msg($conn);
                }
             break;

             case"delete-task";
                 delete_task($conn);
             break;

             case"delete";
                 delete_record($conn);
             break;

             case"top-up";
                top_up_credit($conn);
             break;

             case"del.user-account";
                delete_user_account($conn);
             break;

             case"register";
                 create_user_account_by_admin($conn);
             break;

             case"Submit Hash";
                add_hash($conn);
             break;

             case"run";
                //echo"submit-sql";
                 run_sql($conn);
             break;
         }
     }
}

