<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/08/2018
 * Time: 10:02 AM
 */

if (!isset($_POST['email'])){
    header("location: index.php?u=recovery");
    exit();
}else{
    $email = $_POST['email'];

    $sql = "select * from `user_account` where email ='".$email."'";
    $result = $conn->query($sql);

    if ($result->num_rows > 0){
        $r = $result->fetch_assoc();

        $to = $r['email'];
        $from = "recovery@smsbox.ml";
        $subject = "SMS BOX: User login details";
        $username = $r['username'];
        $password = $r['passwd'];
        $message = " Username:". $r['username']."\r\n Password:". $r['passwd'];

        $header ="From: $from \r\n";
        $header .= "Content-Type: text/html \r\n";

        $mail = mail($to,$subject,$message,$header);

        if ($mail == TRUE){
            echo"email sent";
            //header('Location: ');
        }else{
            echo "error-on-server";
        }
    }else{
        echo"Your email does not exit";
    }



}


