<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 30/09/2018
 * Time: 2:43 PM
 */

?>
<div class="col-lg-6">
    <div class="card">
        <div class="card-header">Crypto Hashing</div>
        <div class="card-body">
            <div class="card-title">
                <h3 class="text-center title-2">Allocate Hashing </h3>
            </div>
            <hr>
            <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"])?>" method="get">
                <div class="form-group has-success">
                    <label class="control-label mb-1">Date</label>
                    <input name="date" type="date" class="form-control" aria-required="true" aria-invalid="false" >
                </div>
                <div class="form-group">
                    <label class="control-label mb-1">Hash</label>
                    <input name="hash" type="text" class="form-control" aria-required="true" aria-invalid="false" value="100.00">
                </div>
                <div>
                    <input type="hidden" name="page" value="model">
                    <input type="hidden" name="token" value="<?php echo $_GET['token']?>">
                    <input type="submit" name="submit" value="Submit Hash" class="btn btn-lg btn-info btn-block fa fa-lock fa-lg">
                </div>
            </form>
        </div>
    </div>
</div>