<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 14/08/2018
 * Time: 4:52 AM
 */


?>
<div class="col-lg-6">
    <div class="card">
        <div class="card-header">Credit Card</div>
        <div class="card-body">
            <div class="card-title">
                <h3 class="text-center title-2">Pay Invoice</h3>
            </div>
            <hr>
            <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"])?>" method="GET" novalidate="novalidate">
                <input type="hidden" name="page" value="model">
                <input type="hidden" name="token" value="<?php echo $_GET['token']?>">
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="cc-date" class="control-label mb-1">Date</label>
                            <input id="cc-date" name="cc-date" type="date" class="form-control cc-exp" value="<?php date("Y-m-d")?>" data-val="true" data-val-required="Please enter the card expiration"
                                   data-val-cc-exp="Please enter a valid month and year" placeholder="YYYY/MM/DD"
                                   autocomplete="cc-exp">
                            <span class="help-block" data-valmsg-for="cc-exp" data-valmsg-replace="true"></span>
                        </div>
                    </div>
                    <div class="col-6">
                        <label for="x_card_code" class="control-label mb-1">Invoice No#</label>
                        <div class="input-group">
                            <input id="x_card_code" name="invoice" type="text" class="form-control cc-cvc" value="<?php echo date("Ymdhis")?>" data-val="true" data-val-required="Please enter the security code"
                                   data-val-cc-cvc="" autocomplete="off">

                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="cc-payment" class="control-label mb-1">Payment amount</label>
                    <input id="cc-pament" name="cc-payment" type="text" class="form-control" aria-required="true" aria-invalid="false" value="100.00">
                </div>
                <div class="form-group">
                    <label for="cc-number" class="control-label mb-1">Mobile Mobile</label>
                    <input id="cc-number" name="cc-number" type="tel" class="form-control cc-number identified visa" value="" data-val="true"
                           data-val-required="Please enter the card number" data-val-cc-number="Please enter a valid card number"
                           autocomplete="cc-number">
                    <span class="help-block" data-valmsg-for="cc-number" data-valmsg-replace="true"></span>
                </div>

                <div>
                    <button id="payment-button" type="submit" name="submit" value="top-up" class="btn btn-lg btn-info btn-block">
                        <i class="fa fa-lock fa-lg"></i>&nbsp;
                        <span id="payment-button-amount">Top-up Credit</span>
                        <span id="payment-button-sending" style="display:none;">Sending…</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="col-lg-6">
    <div class="card">
        <div class="card-header">
            <strong>Buttons</strong> Groups
        </div>
        <div class="card-body card-block">
            <form action="" method="post" class="form-horizontal">
                <div class="row form-group">
                    <div class="col col-md-12">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button class="btn btn-primary">
                                    <i class="fa fa-search"></i> Search
                                </button>
                            </div>
                            <input type="text" id="input1-group2" name="input1-group2" placeholder="Username" class="form-control">
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="card-footer">

        </div>
    </div>
    <!-- TOP CAMPAIGN-->
    <div class="top-campaign">
        <h3 class="title-3 m-b-30">Sales: <?php echo admin_total_sales($conn);?></h3>
        <div class="table-responsive">
            <table class="table table-top-campaign">
                <tbody>
                <?php admin_sale($conn);?>
                </tbody>
            </table>
        </div>
    </div>
    <!--  END TOP CAMPAIGN-->
</div>