<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 03/08/2018
 * Time: 7:48 PM
 */
?>
<div class="col-md-4">
    <div class="card">
        <img class="card-img-top" src="template/images/bg-title-01.jpg" alt="Card image cap">
        <div class="card-body">
            <h4 class="card-title mb-3">Card Image Title</h4>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
                content.
            </p>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="card">
        <img class="card-img-top" src="template/images/bg-title-01.jpg" alt="Card image cap">
        <div class="card-body">
            <h4 class="card-title mb-3">Card Image Title</h4>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
                content.
            </p>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="card">
        <img class="card-img-top" src="template/images/bg-title-01.jpg" alt="Card image cap">
        <div class="card-body">
            <h4 class="card-title mb-3">Card Image Title</h4>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
                content.
            </p>
        </div>
    </div>
</div>
